sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: pip install -e ".[dev]"
script: py.test --cov-report=xml --cov-report=html --cov-report term-missing --cov=awsprofile
after_success:
  - coveralls
